## worksheet 12.3a
Find the best rank-1 approximation to the matrix:


In [3]:
from scipy import linalg
import time
import shutil
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
import matplotlib.pyplot as plt



In [4]:
M = np.asarray([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
U, s, Vh = np.linalg.svd(M, full_matrices=True)
U.shape,  s.shape, Vh.shape
print(U)
print(s)
print(Vh)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
[9.508032   0.77286964]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [6]:
np.dot(np.dot(U[:,:1], s[0]),Vh[0].reshape(1,3))

array([[1.57454629, 2.08011388, 2.58568148],
       [3.75936076, 4.96644562, 6.17353048]])

## worksheet 12 2

In [20]:
U = np.asarray([[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]])
M = np.asarray([[4,0,0,0],[0,3,0,0],[0,0,2,0],[0,0,0,1]])
VT = np.asarray([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0]])
print(U)
print(M)
print(VT)

[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
[[4 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [10]:
np.dot(np.dot(U[:,:2], M[:2,:2]), VT[0:2])


array([[4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0]])

In [21]:
U = np.array([[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]])
M = np.array([[4,0,0,0],[0,3,0,0],[0,0,0,0],[0,0,0,0]])
VT = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0]])
print(U)
print(M)
print(VT)


[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
[[4 0 0 0]
 [0 3 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [22]:
np.dot(np.dot(U, M),VT)

array([[4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0]])